name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Nhập tên phiên bản (ví dụ: v1.0.5)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Filename
        id: filename
        run: |
          # 1. Lấy tên repo
          REPO_NAME=${{ github.event.repository.name }}
          
          # 2. Xác định Version: 
          # Ưu tiên: Input thủ công > Tag name > Branch name
          INPUT_VER="${{ github.event.inputs.version_name }}"
          REF_VER="${{ github.ref_name }}"
          
          if [ -n "$INPUT_VER" ]; then
            VERSION=$INPUT_VER
          else
            VERSION=$REF_VER
          fi
          
          # 3. Tạo tên file cuối cùng
          FULL_NAME="${REPO_NAME}-SusFS-Manager-${VERSION}.zip"
          
          echo "FINAL_NAME=$FULL_NAME" >> $GITHUB_OUTPUT
          echo "VERSION_TAG=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip Source Code
        run: |
          zip -r "${{ steps.filename.outputs.FINAL_NAME }}" . -x ".git/*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.filename.outputs.FINAL_NAME }}
          name: Release ${{ steps.filename.outputs.VERSION_TAG }}
          tag_name: ${{ steps.filename.outputs.VERSION_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
