name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Nút chạy thủ công

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Filename
        id: filename
        run: |
          # Lấy tên repo (ví dụ: PSD)
          REPO_NAME=${{ github.event.repository.name }}
          # Lấy tên tag hoặc tên nhánh (ví dụ: v1.0.0 hoặc main)
          VERSION=${{ github.ref_name }}
          # Tạo biến tên file đầy đủ
          FULL_NAME="${REPO_NAME}-SusFS-Manager-${VERSION}.zip"
          echo "FINAL_NAME=$FULL_NAME" >> $GITHUB_OUTPUT

      - name: Zip Source Code
        run: |
          # Sử dụng biến FINAL_NAME vừa tạo ở trên
          zip -r "${{ steps.filename.outputs.FINAL_NAME }}" . -x ".git/*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.filename.outputs.FINAL_NAME }}
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
